/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/_dashboardLayout'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardLayoutUsersImport } from './routes/_dashboardLayout/users'
import { Route as DashboardLayoutDashboardImport } from './routes/_dashboardLayout/dashboard'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutUsersRoute = DashboardLayoutUsersImport.update({
  path: '/users',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutDashboardRoute = DashboardLayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout/dashboard': {
      id: '/_dashboardLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/users': {
      id: '/_dashboardLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardLayoutUsersImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRoute.addChildren({
    DashboardLayoutDashboardRoute,
    DashboardLayoutUsersRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboardLayout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout.tsx",
      "children": [
        "/_dashboardLayout/dashboard",
        "/_dashboardLayout/users"
      ]
    },
    "/_dashboardLayout/dashboard": {
      "filePath": "_dashboardLayout/dashboard.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/users": {
      "filePath": "_dashboardLayout/users.tsx",
      "parent": "/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
